#!/usr/bin/env node
// Writes one version into the two places that declare it: the manifest and
// `Moviola.version` in src/index.ts. They are a deliberate duplication —
// src/ ships as the readable implementation reference (SPEC §9 v0.4), so it
// states its own version as a literal rather than through a build-time
// define that would read as an undefined global to anyone opening the file.
// test/unit/package.test.ts asserts the two agree, so a stamp that misses
// one fails the suite rather than shipping a runtime that lies about itself.
//
// Only the source files: dist/, examples/ and skill/assets/ carry the same
// string in built bytes and are regenerated by `bun run build` afterwards.
//
// Usage: node scripts/stamp-version.mjs 0.2.0
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))

const version = process.argv[2]
if (!version || !/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(`stamp-version: expected a bare semver argument, got ${version ?? '(nothing)'}`)
  process.exit(1)
}

// Text substitution rather than JSON.parse/stringify for the manifest:
// round-tripping would reformat a file nobody asked to reformat, and the
// diff would stop being reviewable at a glance.
const TARGETS = [
  { file: 'package.json', pattern: /^(\s*"version": ")\d+\.\d+\.\d+(",)$/m },
  { file: 'src/index.ts', pattern: /^(\s*version: ')\d+\.\d+\.\d+(',)$/m },
]

for (const { file, pattern } of TARGETS) {
  const abs = path.join(ROOT, file)
  const before = readFileSync(abs, 'utf8')
  const matches = before.match(new RegExp(pattern, 'gm')) ?? []
  // An ambiguous or absent anchor means the file moved out from under this
  // script. Refusing is the only honest option — a silent no-op here ships
  // a release stamped with the previous version.
  if (matches.length !== 1) {
    console.error(`stamp-version: ${file} has ${matches.length} version declarations, expected 1`)
    process.exit(1)
  }
  writeFileSync(abs, before.replace(pattern, `$1${version}$2`))
}

console.log(`stamped ${version} into ${TARGETS.map(t => t.file).join(' and ')}`)
